extern fn printf(*fmt: i8, ...) -> i32

option State {
    On = (),
    Off = (),
    ErrCode = (i32)
}

fn main() -> i32 {
    auto s = State::On()
    
    match s {
        On => {
            io::printf("Matched On!\n")
        }
        Off => {
            io::printf("Matched Off!\n")
        }
        _ => {
            io::printf("Matched Default/Wildcard!\n")
        }
    }
    
    auto e = State::ErrCode(404)
    match e {
        auto ErrCode(code) => {
            io::printf("Matched ErrCode: %d\n", code)
        }
        _ => {
            io::printf("Ignored\n")
        }
    }
    return 0
}
