extern fn printf(fmt: str, ...) -> i32;

struct Data { v: i32 }

fn main() -> i32 {
    // Parsing check for Logical Operators
    let t = true;
    let f = false;
    let res = t && f || t; 

    if res {
        printf("Logical ops work: result is true\n");
    }

    // Checking Parser Update for Attributes
    let ^#p1 = new Data{v=10};
    printf("Rebindable pointer p1->v: %d\n", p1.v);

    {
        // Nullable Pointer
        let ^?p2 = new Data{v=99};

        // New syntax: 'is' operator for null check. 
        if ^?p2 is ^p2 {
            printf("Nullable pointer is not null (is check)\n");
            printf("p2->v: %d\n", p2.v);
        }
    }
    {
        // Nullable Pointer
        let ^?p3# = null;

        // New syntax: 'is' operator for null check. 
        if ^?p3 is ^p3 {
            printf("Nullable pointer is not null (is check)\n");
        }
        else
        {
            printf("Nullable pointer is null (is check)\n");
        }
    }
    return 0;
}
