import core/io::println

shape Rect (
    w: i32,
    h: i32
)

trait @Shape {
    fn area(self) -> i32
}

trait @Fly {
    fn fly(self) -> i32 {
        return 111
    }
}

impl Rect@Shape {
    fn area(self) -> i32 {
        return self.w * self.h
    }
}

impl Rect@Fly {
    fn fly(self) -> i32 {
        return 222
    }
}

fn main() -> i32 {
    auto r = Rect(w = 10, h = 20)
    auto s = r.area()
    println("Shape Area: {}", s)
    auto f = r.fly()
    println("Fly: {}", f)
    return 0
}
