extern fn printf(*fmt: i8, ...) -> i32;

option State {
    On = (),
    Off = (),
    ErrCode = (i32)
}

fn main() -> i32 {
    auto s = State::On();
    
    match s {
        On => {
            printf("Matched On!\n");
        }
        Off => {
            printf("Matched Off!\n");
        }
        _ => {
            printf("Matched Default/Wildcard!\n");
        }
    }
    
    auto e = State::ErrCode(404);
    match e {
        auto ErrCode(code) => {
            printf("Matched ErrCode: %d\n", code);
        }
        _ => {
            printf("Ignored\n");
        }
    }
    return 0;
}
