
import std/io::println
import std/debug::assert

shape GenericNode<T>(
    val: T
)

alias AliasNode = GenericNode<i32>
type StrongNode = GenericNode<i32>

fn main() -> i32 {
    //auto a# = 10
    //a# = StrongNode(val = 10)
    auto n1# = AliasNode(val = 10)
    auto n2 = GenericNode<i32>(val = 20)
    
    // Alias should be compatible with underlying
    n1# = n2 
    println("Alias work, n1.val: {}, n2.val: {}", n1.val, n2.val)
    assert(n1.val == n2.val, "Alias work")

    auto s1# = StrongNode(val = 30)
    auto s2 = GenericNode<i32>(val = 40)
    // EXCEPT: E0408 Cannot convert type
    s1# = s2 
    println("Strong work, s1.val: {}, s2.val: {}", s1.val, s2.val)
    assert(s1.val == s2.val, "Strong work")

    return 0
}
