// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println
import std/io::println
import std/memory::assert

shape State (
    On |
    Off |
    ErrCode(i32)
)

fn main() -> i32 {
    auto s = State::On()
    
    match s {
        On => {
            println("Matched On!\n")
            assert(true, "Matched On")
        }
        Off => {
            println("Matched Off!\n")
        }
        _ => {
            println("Matched Default/Wildcard!\n")
        }
    }
    
    auto e = State::ErrCode(404)
    match e {
        auto ErrCode(code) => {
            println("Matched ErrCode: {}", code)
            assert(code == 404, "ErrCode mismatch")
        }
        _ => {
            println("Ignored\n")
        }
    }
    return 0
}
