// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import std/io::println
import std/memory
import core/traits

shape Point(x:i32, y:i32)
impl Point@encap {
    fn drop(self#) {
        println("Dropping Point x:{} y:{}", self.x, self.y)
    }
}

shape Resource (
    id: i32,
    point: Point
    )

impl Resource@encap {
    fn drop(self#) {
        println("Dropping Resource {}", self.id)
    }
}

fn main() -> i32 {
    println("Start")
    {
        auto r1 = Resource(id=1,point=Point(x=1,y=2))
        println("Inside block")
    }
    println("After block")

    auto ^#p1 = new Resource(id=11, point=Point(x=1,y=2))
    auto ~s1 = new Resource(id=21, point=Point(x=1,y=2))

    //auto ^p2 = ^p1
    println("will rebind ^#p1")
    ^#p1 = new Resource(id=111, point=Point(x=1,y=2))
    println("after rebind ^#p1")

    auto ~s2 = ~s1
    
    auto r2 = Resource(id=22, point=Point(x=1,y=2))
    println("End of main")
    return 0
}
