// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println
import std/debug::assert

shape Rect (
    width: i32,
    height: i32
)

impl Rect {
    pub fn area(self) -> i32 {
        return self.width * self.height
    }
    
    pub fn perimeter(self) -> i32 {
        return (self.width + self.height) * 2
    }
}

fn main() -> i32 {
    auto r = Rect(width = 10, height = 20)
    
    // Test method call
    auto a = r.area()
    println("Area: {}", a)
    assert(a == 200, "Area mismatch")
    
    auto p = r.perimeter()
    println("Perimeter: {}", p)
    assert(p == 60, "Perimeter mismatch")
    return 0
}
