// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println
import std/debug::assert

fn main() -> i32 {
    // ---------------------------------------------------
    // Step 1: 源头定义 (Sources)
    // ---------------------------------------------------
    // 关键修正：为了让 ptr 能修改它们，arr1 和 arr2 都必须是可写的 (#)！
    auto arr1# = [10, 20]
    auto arr2# = [99, 88] // 如果这里没有 #，下面auto *#ptr# = *arr1 时会报编译错误 因为灵魂的可变性不可随意更改

    unsafe {
        // ---------------------------------------------------
        // Step 2: 声明双重可变指针 (The Double Agent)
        // ---------------------------------------------------
        // auto *#ptr#
        //  *# : Identity is Swappable (指针本身可变，可以指别人)
        //  ptr# : Soul is Writable (指向的内容可变，可以改值)
        // 右边：从 arr1 取地址。编译器会检查 arr1 是否有 # 权限。
        auto *#ptr# = *arr1 
        
        // ---------------------------------------------------
        // 场景 A：修改灵魂 (Mutate Value)
        // ---------------------------------------------------
        // 规则：修改值，必须在访问路径末尾出示 #
        
        ptr[0] = 30         // ✅ 修改 ptr[0]。语义：Access Soul -> Write.
        
        // 语义：Offset to 1 -> Access Soul -> Write.
        ptr[1] = 40      
        
        assert(arr1[0] == 30, "arr1[0] should be 30")
        assert(arr1[1] == 40, "arr1[1] should be 40")

        // ---------------------------------------------------
        // 场景 B：重绑身份 (Rebind Identity)
        // ---------------------------------------------------
        // 规则：修改指向，必须在 * 后出示 #
        // 此时不需要 ptr#，因为我们改的是地址，不是值。
        
        *ptr = *arr2     // ✅ 指针重定向！指向了 arr2
        
        // ---------------------------------------------------
        // 场景 C：在新地址上行使权力
        // ---------------------------------------------------
        // 验证身份已变
        assert(ptr == 99, "ptr should be 99") // ptr[0] 现在是 arr2[0]
        
        // 继续修改灵魂 (因为 ptr# 依然拥有写权限，且 arr2# 允许被写)
        ptr = 100        // ✅ 修改 arr2[0]
        assert(arr2[0] == 100, "arr2[0] should be 100")
    }
    return 0
}