
import std/io::println
import std/memory::assert

shape Node(
    val: i32,
    ^?next: Node
)

pub fn main() -> i32 {
    unsafe {
        // User's logic + Print checks
        auto ^head = new Node(val=101, ^?next=unset)  
        //println("head: {}", head.val)
        //assert(head.val == 101, "check head.val")
        // Push 1
        {
            auto &#iter = &head
            for auto i in [1,2,3,4,5] {
                iter.^next = new Node(val=i, ^?next=unset)
                println("[{}]pushed: {}", i, iter.val)
                &#iter = iter.^next
            }
            iter.^?next = nullptr
        }

        auto &#iter = &head
        loop {
            println("iter: {}", iter.val)
            if (iter.^next == nullptr) {
                assert(iter.^next == nullptr, "check null")
                break
            }
            &#iter = iter.^next
        }
    }
    return 0
}