
import std/io::println
import std/memory::assert

shape Node(
    val: i32,
    ~?next: Node
)
impl Node {
    fn unwrap(~?self: Node) -> &Node <- self {
        if ~?self is ~self {
            return &self
        }
        assert(false, "unwrap null")
        return &self
    }
}

fn unwrap(~?p: Node) -> &Node <- p {
    if ~?p is ~p {
        return &p
    }
    assert(false, "unwrap null")
    return &p
}

pub fn main() -> i32 {
    // User's logic + Print checks
    auto ~#head = new Node(val=0, ~?next=nullptr)  
    println("head: {}", head.val)
    assert(head.val == 0, "check head.val")
    // Push 1
    {
        for auto i in [1,2,3,4,5] {
            auto ~next = ~head
            ~#head = new Node(val=i, ~?next=~next)
            println("[{}]pushed: {}", i, head.val)
            assert(head.val == i, "check head.val")
        }
    }
    
    auto ~#cursor = ~head 
    auto i# = 5
    loop {
        assert(i >= 0, "check i >= 0")
        println("[{}]val: {}", i, cursor.val)
        assert(cursor.val == i, "check cursor.val")
        i# -= 1
        if i < 0 {
            break
        }
        
        if cursor.~?next is cursor.~next {
            ~#cursor = cursor.~next 
        } else {
            break
        }
    }
    return 0
}