import std/io::println
import std/io::println
import std/memory::assert

shape State (
    On |
    Off |
    ErrCode(i32)
)

fn main() -> i32 {
    auto s = State::On()
    
    match s {
        On => {
            println("Matched On!\n")
            assert(true, "Matched On")
        }
        Off => {
            println("Matched Off!\n")
        }
        _ => {
            println("Matched Default/Wildcard!\n")
        }
    }
    
    auto e = State::ErrCode(404)
    match e {
        auto ErrCode(code) => {
            println("Matched ErrCode: {}", code)
            assert(code == 404, "ErrCode mismatch")
        }
        _ => {
            println("Ignored\n")
        }
    }
    return 0
}
