import core/io::println

fn main() -> i32 {
    auto i# = 0
    while i < 5 {
        println("while: {}", i)
        i# += 1
        if i == 3 { 
            println("i = {}, break", i)
            break 
        }
        if i == 2 { 
            println("i = {}, continue", i)
            continue 
        }
    }

    // Range loop
    for auto x in [0,1,2] {
        println("for range: {}", x)
    }

    // Loop as expression with yield
    auto res = loop {
        if i > 10 { 
            println("i = {}, break", i)
            break 42 
        }
        i# += 1
    }
    println("loop result: {}", res)

    // While as expression with yield
    auto j# = 0
    auto res2 = while j < 10 {
        if j == 5 {
            println("j = {}, break", j)
            break j * 2 
        }
        j# += 1
    }
    or {
        println("or, pass\n")
        pass 0
    }
    println("while result: {}", res2)
    return 0
}
