
import std/io::println
import std/memory
import core/traits

shape Point(x:i32, y:i32)
impl Point@encap {
    fn drop(self#) {
        println("Dropping Point x:{} y:{}", self.x, self.y)
    }
}

shape Resource (
    id: i32,
    point: Point
    )

impl Resource@encap {
    fn drop(self#) {
        println("Dropping Resource {}", self.id)
    }
}

fn main() -> i32 {
    println("Start")
    {
        auto r1 = Resource(id=1,point=Point(x=1,y=2))
        println("Inside block")
    }
    println("After block")

    auto ^#p1 = new Resource(id=11)
    auto ~s1 = new Resource(id=21)

    //auto ^p2 = ^p1
    println("will rebind ^#p1")
    ^#p1 = new Resource(id=111)
    println("after rebind ^#p1")

    auto ~s2 = ~s1
    
    auto r2 = Resource(id=2)
    println("End of main")
    return 0
}
