// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println
import std/memory::assert
import core/marker::{@Clone,@Default}

shape Dummy (
    id: i32
)

impl Dummy@Clone {
    pub fn clone(self) {
        // Just for parsing test
    }
}

impl Dummy@Default {
    pub fn init(self) {
        // Just for parsing test
    }
}

fn main() -> i32 {
    auto d = Dummy(id = 1)
    d.clone()
    d.init()
    
    println("Core traits parsed and called successfully.")
    assert(d.id == 1, "d.id mismatch")
    return 0
}
