import std/io::println

shape Rect (
    width: i32,
    height: i32
)

impl Rect {
    fn area(self) -> i32 {
        return self.width * self.height
    }
    
    fn perimeter(self) -> i32 {
        return (self.width + self.height) * 2
    }
}

fn main() -> i32 {
    auto r = Rect(width = 10, height = 20)
    
    // Test method call
    auto a = r.area()
    println("Area: {}", a)
    
    auto p = r.perimeter()
    println("Perimeter: {}", p)
    return 0
}
