import std/io::println

shape Data (v: i32)

fn main() -> i32 {
    // Parsing check for Logical Operators
    auto t = true
    auto f = false
    auto res = t && f || t

    if res {
        println("Logical ops work: result is true\n")
    }

    // Checking Parser Update for Attributes
    auto ^#p1 = new Data(v=10)
    println("Rebindable pointer p1->v: {}", p1.v)

    {
        // Nullable Pointer
        auto ^?p2 = new Data(v=99)

        // New syntax: 'is' operator for nullptr check. 
        if ^?p2 is ^p2 {
            println("Nullable pointer is not nullptr (is check)\n")
            println("p2->v: {}", p2.v)
        }
    }
    {
        // Nullable Pointer
        auto ^?p3:Data = nullptr

        // New syntax: 'is' operator for nullptr check. 
        if ^?p3 is ^p3 {
            println("Nullable pointer is not nullptr (is check)\n")
        }
        else
        {
            println("Nullable pointer is nullptr (is check)\n")
        }
    }
    return 0
}
