import std/io::println

shape Data (
    v: i32
)

fn main() -> i32 {
    auto ^?p = new Data(v = 42)
    
    // Narrowing: ^?p is ^p
    if ^?p is ^p {
        println("Success: p.v = {}", p.v)
    } else {
        println("Failure: p is null\n")
    }

    auto ^?q# = null
    if ^?q is ^q {
        println("Error: q should be null\n")
    } else {
        println("Success: q confirmed null\n")
    }

    return 0
}
