import std/io::println
import std/memory::assert
import core/marker::{@Clone,@Default}

shape Dummy (
    id: i32
)

impl Dummy@Clone {
    pub fn clone(self) {
        // Just for parsing test
    }
}

impl Dummy@Default {
    pub fn init(self) {
        // Just for parsing test
    }
}

fn main() -> i32 {
    auto d = Dummy(id = 1)
    d.clone()
    d.init()
    
    println("Core traits parsed and called successfully.")
    assert(d.id == 1, "d.id mismatch")
    return 0
}
