import std/io::println
import std/memory::assert

// Allowed Types Union
shape SafeUnionType (
    as c: u8 |
    as wc: u32 |
    as b: u16
)

fn main() -> i32 {
    auto u = SafeUnionType(wc = 65 as u32)
    println("Union access with u8: {}", u.c)
    println("Union access with u32: {}", u.wc)
    println("Union access with u16: {}", u.b)
    assert(u.c == 65, "Union access with u8 mismatch")
    assert(u.wc == 65, "Union access with u32 mismatch")
    assert(u.b == 65, "Union access with u16 mismatch")
    
    auto u2 = SafeUnionType(wc = 0x0000ABCD as u32)
    println("Union access with u8: {}", u2.c)
    println("Union access with u32: {}", u2.wc)
    println("Union access with u16: {}", u2.b)
    assert(u2.c == 205, "Union access with u8 mismatch")
    assert(u2.wc == 0xAABBCCDD, "Union access with u32 mismatch")
    assert(u2.b == 65, "Union access with u16 mismatch")
    return 0
}
